easy_admin:
    site_name: Conference Guestbook

    design:
        menu:
            - { route: 'homepage', label: 'Back to the website', icon: 'home' }
            - { entity: 'Conference', label: 'Conferences', icon: 'map-marker' }
            - { entity: 'Comment', label: 'Comments', icon: 'comments' }

    entities:
        Conference:
            class: App\Entity\Conference
        Comment:
            class: App\Entity\Comment
            list:
                fields:
                    - author
                    - { property: 'email', type: 'email' }
                    - { property: 'createdAt', type: 'datetime' }
                    - state
                sort: ['createdAt', 'ASC']
                filters: ['conference']
            edit:
                fields:
                    - { property: 'email', type: 'email' }
                    - { property: 'photoFilename', type: 'file', 'base_path': '/uploads/photos', label: 'Photo' }
                    - { property: 'createdAt', type: 'datetime', type_options: { attr: { readonly: true } } }
                    - author
                    - { property: 'state' }
                    - { property: 'email', type: 'email' }
                    - text
